# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  displayName: 'Install Terraform 0.13.5'
  inputs:
    terraformVersion: 0.13.5

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
  displayName: 'Terraform : init'
  inputs:
    provider: aws
    workingDirectory: '$(System.DefaultWorkingDirectory)/amachira/azure-terraform-aws-CICD'
    backendServiceAWS: 'azureterraforms3'
    backendAWSBucketName: 'anagh-terraform-remote-state'
    backendAWSKey: 'tf/azure-terraform-aws-CICD/anaghterraformrs.tfstate'
